apiVersion: v1
kind: Namespace
metadata:
  name: sre-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sre-production
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  APP_ENV: "production"
